require: rubocop-rspec

AllCops:
  Include:
    - "**/Rakefile"
    - "**/config.ru"
    - "**/Gemfile"
  Exclude:
    - "bin/*"
    - "chef/**/*"
    - "db/**/*"
    - "features/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "selenium_features/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
  RunRailsCops: true

### Metrics ####################################################################

Metrics/AbcSize:
  Max: 15   # default

Metrics/BlockNesting:
  Max: 3    # default

Metrics/ClassLength:
  Max: 150  # default: 100

Metrics/ModuleLength:
  Max: 150  # default: 100

Metrics/CyclomaticComplexity:
  Max: 6    # default

Metrics/LineLength:
  Max: 80   # default
  AllowURI: true

Metrics/MethodLength:
  Max: 15   # default: 10

Metrics/ParameterLists:
  Max: 5    # default

Metrics/PerceivedComplexity:
  Max: 7    # default

### Style ######################################################################

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# Not enforcing single space before first arg to allow tabular alignments when
# using DSL methods (e.g. FactoryGirl).
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Not enforcing %i() arrays, because they are too similar to %w() and don't have
# proper syntax highlighting support for differentiating between them.
Style/SymbolArray:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

### Rails ######################################################################

# It would be better to handle time zones properly, but since the application
# only serves customers in the UK, it doesn't hurt to disable the following two.
Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false
